"""Streamlit dashboard: Overview, Tier Explorer, Ask the Data.

    streamlit run dashboard/app.py

Runs entirely from the committed demo database (demo/demo.sqlite, pre-aggregated, ~2 MB), so it
works on Streamlit Community Cloud without Postgres or the raw dataset.

Ask the Data has two modes:
  demo (default)  the 55 eval questions with the cached answers from the frozen eval runs:
                  question, SQL, result, answer and the graded correctness label.
  live            only when BOTH secrets exist: GEMINI_API_KEY and DATABASE_URL (a Postgres
                  holding the warehouse). Hard rate limit: LIVE_PER_SESSION per browser session
                  and LIVE_PER_HOUR across all users of the app.
"""
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:  # Streamlit puts dashboard/ on the path, not the repo root
    sys.path.insert(0, str(ROOT))

import pandas as pd  # noqa: E402
import streamlit as st  # noqa: E402

from dashboard import charts  # noqa: E402
from service.ratelimit import RateLimiter  # noqa: E402
from service.store import DemoStore  # noqa: E402
from tiering.score import explain  # noqa: E402

LIVE_PER_SESSION = 5
LIVE_PER_HOUR = 30

st.set_page_config(page_title="Retail Sales Platform", page_icon="📊", layout="wide")


@st.cache_resource
def store() -> DemoStore:
    return DemoStore()


@st.cache_resource
def live_limiter() -> RateLimiter:
    return RateLimiter(LIVE_PER_HOUR, per_seconds=3600)   # shared by every session of this app


def secret(name: str) -> str | None:
    try:
        return st.secrets.get(name) or os.environ.get(name)
    except Exception:  # no secrets file at all (local run)
        return os.environ.get(name)


def is_dark() -> bool:
    try:
        return st.context.theme.type == "dark"
    except Exception:
        return False


S = store()
K = {k: v["value"] for k, v in S.kpis.items()}
DARK = is_dark()

st.title("Retail Sales Platform")
st.caption("UK online wholesaler, Dec 2009 – Dec 2011 (UCI Online Retail II, CC BY 4.0). "
           f"Demo data built {S.meta['built_at'][:10]} from the full pipeline; every number is generated by code.")

overview, explorer, ask = st.tabs(["Overview", "Tier Explorer", "Ask the Data"])

# ---- Overview ---------------------------------------------------------------------------------
with overview:
    c = st.columns(4)
    c[0].metric("Revenue (GBP)", f"£{float(K['revenue_gbp']) / 1e6:.2f}M",
                help=f"{int(K['clean_rows']):,} sales lines from {int(K['raw_rows']):,} raw rows")
    c[1].metric("Customers", f"{int(K['customers']):,}",
                help=f"Top 10% of customers bring {float(K['top10_share_pct']):.1f}% of revenue")
    n_checks = int(K["quality_pass"]) + int(K["quality_warn"]) + int(K["quality_fail"])
    c[2].metric("Quality checks failing", f"{K['quality_fail']} of {n_checks}",
                help=f"{K['quality_pass']} pass, {K['quality_warn']} warn (seasonal peaks, partial Dec 2011); "
                     f"dbt: {K['dbt_tests_pass']} tests passing")
    c[3].metric("Migration parity", f"{float(K['parity_clean_pct']):.0f}% clean run",
                help=f"An injected silent bug dropped parity to {float(K['parity_injected_pct']):.1f}% and was caught")
    c = st.columns(4)
    c[0].metric("Tier 1 share of next-6-month revenue", f"{float(K['tier1_capture_pct']):.1f}%",
                delta=f"{float(K['tier1_capture_pct']) - float(K['monetary_capture_pct']):+.1f} pts vs monetary-only",
                delta_color="normal")
    c[1].metric("v2 learned weights, top 10% share", f"{float(K['v2_capture_pct']):.1f}%")
    c[2].metric("AI analyst: confidently wrong (v1 → v3)",
                f"{float(K['cw_v1_pct']):.1f}% → {float(K['cw_v3_pct']):.1f}%",
                help=f"{K['cw_v1_count']} → {K['cw_v3_count']} answers, pooled over 3 Gemini models")
    c[3].metric("Scores match v1 after dbt migration", "Yes, bit for bit" if K["dbt_matches_v1"] == "1" else "No")

    left, right = st.columns(2)
    with left:
        st.subheader("Revenue peaks every Sep–Nov")
        st.altair_chart(charts.monthly_revenue(S.table("monthly"), DARK), width="stretch")
    with right:
        st.subheader("Tiers rank future revenue in order")
        st.altair_chart(charts.tier_future_revenue(S.scored.reset_index(), DARK), width="stretch")
    left, right = st.columns(2)
    with left:
        st.subheader("Top 10% by tier score capture 58% of next-period revenue; monetary-only captures 62%")
        st.altair_chart(charts.capture_curve(S.scored.reset_index(), DARK), width="stretch")
        st.caption("Dashed diagonal = random targeting; the vertical line marks the top 10%.")
    with right:
        st.subheader("Pipeline quality checks (last run)")
        qc = S.table("quality_checks")
        st.dataframe(qc, hide_index=True, width="stretch", height=330)
    with st.expander("Show the chart data as tables"):
        st.dataframe(S.table("monthly"), hide_index=True)
        st.dataframe(S.table("tier_summary"), hide_index=True)
        st.dataframe(S.table("tier_methods"), hide_index=True)

# ---- Tier Explorer ----------------------------------------------------------------------------
with explorer:
    scored = S.scored
    f1, f2 = st.columns([1, 2])
    tier_filter = f1.selectbox("Tier", ["All", "Tier 1", "Tier 2", "Tier 3", "Tier 4"])
    pool = scored if tier_filter == "All" else scored[scored["tier"] == tier_filter]
    ids = pool.sort_values("rank").index.tolist()
    default = ids.index(12346) if 12346 in ids else 0
    cid = f2.selectbox(f"Customer ({len(ids):,} in this tier, best-ranked first)", ids, index=default,
                       format_func=lambda i: f"{i}  ·  {scored.at[i, 'tier']}  ·  rank {scored.at[i, 'rank']:,}  ·  "
                                             f"{scored.at[i, 'country']}")
    ex = explain(cid, scored)
    row = scored.loc[cid]
    m = st.columns(4)
    m[0].metric("Tier", ex["tier"])
    m[1].metric("Score", f"{ex['score']:.1f} / 100", help=f"Rank {ex['rank']:,} of {ex['customers']:,}")
    m[2].metric("Country", row["country"])
    m[3].metric("Actual revenue, Jun–Nov 2011", f"£{row['future_revenue']:,.2f}",
                help="What the customer went on to spend after being scored on 1 Jun 2011")
    st.subheader("Why this tier: points each input adds to the score")
    bd = pd.DataFrame(ex["breakdown"])
    st.altair_chart(charts.contributions(bd, DARK), width="stretch")
    st.dataframe(bd[["label", "value", "percentile", "weight", "points"]].rename(columns={
        "label": "Input", "value": "Value", "percentile": "Percentile (100 = best)", "weight": "Weight",
        "points": "Points"}), hide_index=True, width="stretch")
    st.caption("Each input is turned into a 0–100 percentile rank against all 4,908 scored customers "
               "(lower is better for recency, cancellations and irregularity), then weighted. "
               "Weights: recency 0.25, frequency 0.25, revenue 0.30, breadth 0.10, cancellations 0.10.")

# ---- Ask the Data -----------------------------------------------------------------------------
with ask:
    live_ok = bool(secret("GEMINI_API_KEY") and secret("DATABASE_URL"))
    modes = ["Demo: cached eval answers"] + (["Live: ask Gemini"] if live_ok else [])
    mode = st.radio("Mode", modes, horizontal=True)
    if not live_ok:
        st.info("Demo mode: these are the 55 questions of the frozen evaluation set, with the answers the "
                "analyst actually gave, each graded against a hand-written reference query. Live mode appears "
                "only when the app has both a GEMINI_API_KEY and a DATABASE_URL secret.")

    if mode.startswith("Demo"):
        qs = S.questions()
        c1, c2, c3 = st.columns([3, 1, 1])
        labels = {r.question: f"[{r.difficulty}] {r.question}" for r in qs.itertuples()}
        q = c1.selectbox("Question", qs["question"], format_func=labels.get)
        model = c2.selectbox("Model", ["gemini-3.5-flash", "gemini-3.5-flash-lite", "gemini-3.1-flash-lite"])
        version = c3.selectbox("Prompt", ["v3", "v2", "v1"], format_func={
            "v1": "v1 baseline", "v2": "v2 + glossary", "v3": "v3 + self-check"}.get)
        a = S.cached_answer(q, model, version)
        color, icon = charts.STATUS[a["outcome"]]
        st.markdown(f"#### {icon} {charts.OUTCOME_LABEL[a['outcome']]}")
        st.markdown(f"**Answer:** {a['answer']}")
        st.caption("Abstained." if a["abstained"] else
                   "Answer text is rendered from the SQL result (the eval runs don't generate prose).")
        if a["sql"]:
            st.code(a["sql"], language="sql")
        if a["error"]:
            st.error(a["error"])
        if a["rows"]:
            st.dataframe(pd.DataFrame(a["rows"], columns=a["columns"]), hide_index=True, width="stretch")
            if a["row_count"] > len(a["rows"]):
                st.caption(f"Showing {len(a['rows'])} of {a['row_count']} rows.")
        if a["outcome"] not in ("correct", "refused") and a["reference_sql"]:
            with st.expander("Reference answer (hand-written SQL)", expanded=True):
                st.code(a["reference_sql"], language="sql")
                st.dataframe(pd.DataFrame(a["reference_rows"], columns=a["reference_columns"]), hide_index=True)
        with st.expander("How every model and prompt version did on this question"):
            grid = S.answers[S.answers["question"] == q].pivot(index="model", columns="prompt_version",
                                                               values="outcome")
            st.dataframe(grid.map(lambda o: f"{charts.STATUS[o][1]} {o}"), width="stretch")
    else:  # live mode: not exercised in development (no API credits); see README
        if "live_used" not in st.session_state:
            st.session_state.live_used = 0
        left = LIVE_PER_SESSION - st.session_state.live_used
        st.caption(f"{left} live questions left in this session; at most {LIVE_PER_HOUR} per hour across all users.")
        q = st.text_input("Your question", max_chars=300)
        if st.button("Ask", disabled=left <= 0 or not q):
            if not live_limiter().allow():
                st.error("The hourly live-question limit for this demo has been reached. Try demo mode.")
            else:
                st.session_state.live_used += 1
                os.environ.setdefault("GEMINI_API_KEY", secret("GEMINI_API_KEY") or "")
                os.environ.setdefault("DATABASE_URL", secret("DATABASE_URL") or "")
                try:
                    from analyst.agent import Analyst

                    ans = Analyst(prompt_version="v3", narrate=True, use_cache=False).ask(q)
                    st.markdown(f"**Answer:** {ans.answer}")
                    if ans.sql:
                        st.code(ans.sql, language="sql")
                        st.dataframe(pd.DataFrame(ans.rows, columns=ans.columns), hide_index=True)
                    st.caption("Live answers are not graded: correctness is only known for the eval questions.")
                except Exception as err:  # fallback: say so, never guess
                    st.error(f"The analyst failed ({type(err).__name__}); no answer is shown rather than a guess.")
